# Generated by Django 5.2.8 on 2025-11-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='audio_file',
            field=models.FileField(default='audio/sample-3s.mp3', upload_to='audio/'),
        ),
    ]
