# Generated by Django 5.2.8 on 2025-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_details_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='audio_file',
            field=models.FileField(default='audio/sample-3s.mp3', upload_to='audio_player/'),
        ),
    ]
