# Generated by Django 5.2.8 on 2025-11-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_details_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idval', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
